# Generated by Django 5.2.3 on 2025-06-16 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NhapHang', '0002_delete_baotri_remove_chitietdon_don_xuat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuaHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_cua_hang', models.CharField(max_length=20, unique=True)),
                ('ten_cua_hang', models.CharField(max_length=100)),
                ('dia_chi', models.TextField()),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15, null=True)),
                ('khu_vuc', models.CharField(blank=True, max_length=50, null=True)),
                ('trang_thai', models.CharField(choices=[('Hoạt_động', 'Hoạt động'), ('Tạm_dừng', 'Tạm dừng')], default='Hoạt_động', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cửa hàng',
                'verbose_name_plural': 'Cửa hàng',
                'db_table': 'cua_hang',
            },
        ),
        migrations.CreateModel(
            name='DonXuat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_don', models.CharField(max_length=20, unique=True)),
                ('ngay_tao', models.DateField()),
                ('ngay_giao', models.DateField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('Chờ_xuất', 'Chờ xuất'), ('Đang_xuất', 'Đang xuất'), ('Hoàn_thành', 'Hoàn thành'), ('Hủy', 'Hủy')], default='Chờ_xuất', max_length=10)),
                ('qr_code_data', models.TextField(blank=True, null=True)),
                ('da_in_qr', models.BooleanField(blank=True, default=False, null=True)),
                ('nguoi_tao', models.CharField(blank=True, max_length=50, null=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cua_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaoDon.cuahang')),
            ],
            options={
                'db_table': 'don_xuat',
            },
        ),
        migrations.CreateModel(
            name='ChiTietDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('san_pham', models.CharField(max_length=100)),
                ('so_luong_can', models.IntegerField()),
                ('pallet_assignments', models.JSONField(blank=True, null=True)),
                ('da_xuat_xong', models.BooleanField(blank=True, default=False, null=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('don_xuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaoDon.donxuat')),
            ],
            options={
                'db_table': 'chi_tiet_don',
            },
        ),
        migrations.CreateModel(
            name='LichSuXuatNhap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_giao_dich', models.CharField(max_length=4)),
                ('so_luong', models.IntegerField()),
                ('nguoi_thuc_hien', models.CharField(blank=True, max_length=50, null=True)),
                ('ngay_thuc_hien', models.DateTimeField(blank=True, null=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('don_xuat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TaoDon.donxuat')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NhapHang.pallets')),
            ],
            options={
                'db_table': 'lich_su_xuat_nhap',
            },
        ),
        migrations.CreateModel(
            name='ThuTuXuatHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('san_pham', models.CharField(max_length=100)),
                ('thu_tu_mac_dinh', models.IntegerField()),
                ('thu_tu_tuy_chinh', models.IntegerField(blank=True, null=True)),
                ('thoi_gian_uoc_tinh', models.IntegerField(blank=True, null=True)),
                ('khoang_cach_uoc_tinh', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('don_xuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaoDon.donxuat')),
            ],
            options={
                'db_table': 'thu_tu_xuat_hang',
            },
        ),
    ]
